//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamics365CustomizingDownloader.MultiLanguage {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedLables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedLables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamics365CustomizingDownloader.MultiLanguage.LocalizedLables", typeof(LocalizedLables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EncryptionKey_Btn_SaveEncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey_Btn_SaveEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an Encryption Key/Password 
        ///for your CRM Connections :.
        /// </summary>
        public static string EncryptionKey_Lbl_PleaseChooseEncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey_Lbl_PleaseChooseEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remember this Key, as you need it 
        ///every time you start this application.
        /// </summary>
        public static string EncryptionKey_Lbl_PleaseRemember {
            get {
                return ResourceManager.GetString("EncryptionKey_Lbl_PleaseRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Key does not match!.
        /// </summary>
        public static string EncryptionKey_MessageBox_KeyDoesNotMatch {
            get {
                return ResourceManager.GetString("EncryptionKey_MessageBox_KeyDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Encryption Key.
        /// </summary>
        public static string EncryptionKey_MessageBox_KeyDoesNotMatchCaption {
            get {
                return ResourceManager.GetString("EncryptionKey_MessageBox_KeyDoesNotMatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Encryption Key.
        /// </summary>
        public static string EncryptionKey_MessageBox_NoKeySpecified {
            get {
                return ResourceManager.GetString("EncryptionKey_MessageBox_NoKeySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Key entered.
        /// </summary>
        public static string EncryptionKey_MessageBox_NoKeySpecifiedCaption {
            get {
                return ResourceManager.GetString("EncryptionKey_MessageBox_NoKeySpecifiedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Name.
        /// </summary>
        public static string MainWindow_Dtg_Solutions_UniqueName {
            get {
                return ResourceManager.GetString("MainWindow_Dtg_Solutions_UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string MainWindow_Lbl_Connection {
            get {
                return ResourceManager.GetString("MainWindow_Lbl_Connection", resourceCulture);
            }
        }
    }
}
